routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\IndexController;
use App\Http\Controllers\PareceristaController;
use App\Http\Controllers\EstagioController;
use App\Http\Controllers\VagaController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\AvisoController;
use App\Http\Controllers\PDFsController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\EstagioWorkflowController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\EstatisticaController;
use App\Http\Controllers\Auth\LoginEmpresaController;
use App\Http\Controllers\Auth\LoginUspController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\EstudanteController;
use App\Http\Controllers\GeneralSettingsController;

Route::get('/',[IndexController::class, 'index'])->name('login');
Route::get('/home',[IndexController::class, 'index'])->name('home');

# Models
Route::resource('/pareceristas',PareceristaController::class);
Route::resource('/estagios',EstagioController::class);
Route::resource('/vagas',VagaController::class);
Route::resource('/empresas', EmpresaController::class);
Route::resource('/avisos',AvisoController::class);
Route::resource('/files', FileController::class);
Route::resource('/estatisticas',EstatisticaController::class);

# vagas
Route::post('/aprovar/{vaga}',[VagaController::class,'aprovar'])->name('vagas.aprovar');
Route::post('/reprovar/{vaga}',[VagaController::class,'reprovar'])->name('vagas.reprovar');

#PDF's
Route::get('/pdfs/termo/{estagio}', [PDFsController::class, 'termo']);
Route::get('/pdfs/renovacao/{estagio}', [PDFsController::class, 'renovacao']);
Route::get('/pdfs/aditivo/{estagio}', [PDFsController::class, 'aditivo']);
Route::get('/pdfs/rescisao/{estagio}', [PDFsController::class, 'rescisao']);
Route::get('/pdfs/parecer/{estagio}', [PDFsController::class, 'parecer']);
Route::get('/pdfs/lista_empresas', [PDFsController::class, 'lista_empresas']);


#E-mails
Route::get('/emails/enviar_para_analise_tecnica/{estagio}', [EmailController::class, 'enviar_para_analise_tecnica']);
Route::get('/emails/enviar_para_estudante/{estagio}', [EmailController::class, 'enviar_para_estudante']);
Route::get('/emails/enviar_para_analise_tecnica_renovacao/{estagio}', [EmailController::class, 'enviar_para_analise_tecnica_renovacao']);
Route::get('/emails/enviar_para_parecerista/{estagio}', [EmailController::class, 'enviar_para_parecerista']);
Route::get('/emails/alteracao/{estagio}', [EmailController::class, 'alteracao']);
Route::get('/emails/alteracao_empresa/{estagio}', [EmailController::class, 'alteracao_empresa']);
Route::get('/emails/analise_rescisao/{estagio}', [EmailController::class, 'analise_rescisao']);
Route::get('/emails/rescisao_empresa/{estagio}', [EmailController::class, 'rescisao_empresa']);


# Login comunidade USP
Route::get('login/usp', [LoginUspController::class, 'redirectToProvider']);
Route::get('callback', [LoginUspController::class, 'handleProviderCallback']);
Route::post('/logout', [LogoutController::class, 'logout']);

# logins secrets
Route::post('/logandoComoEmpresa/{cnpj}', [EmpresaController::class,'logandoComoEmpresa']);
Route::post('/adminLogandoComoParecerista/{codpes}', [PareceristaController::class,'adminLogandoComoParecerista']);
Route::get('/acessar_outra_empresa', [EmpresaController::class,'acessar_outra_empresa']);

# Login empresa
Route::get('login/empresa', [LoginEmpresaController::class,'create']);
Route::post('login/empresa', [LoginEmpresaController::class,'store']);
Route::get('login/empresa/check', [LoginEmpresaController::class,'empresa'])->name('login_empresa');
Route::get('login/empresa_perdisenha', [LoginEmpresaController::class,'create']);

# Rotas para empresa
Route::get('/empresa_update', [EmpresaController::class,'empresa_update']);

# rotas para workflow do estágio

# Rotas Análise Técnica
Route::post('/analise_tecnica/{estagio}', [EstagioWorkflowController::class,'analise_tecnica']);
Route::post('/enviar_para_analise_tecnica/{estagio}', [EstagioWorkflowController::class,'enviar_para_analise_tecnica']);
Route::post('/mover_analise_tecnica/{estagio}', [EstagioWorkflowController::class,'mover_analise_tecnica']);
Route::post('/enviar_assinatura/{estagio}', [EstagioWorkflowController::class,'enviar_assinatura']);

# Rotas Assinatura
Route::get('/retornar_assinatura/{estagio}', [EstagioWorkflowController::class,'retornar_assinatura']);

# Rotas Análise Acadêmica
Route::post('/analise_academica/{estagio}', [EstagioWorkflowController::class,'analise_academica']);
Route::get('/voltar_analise_academica/{estagio}', [EstagioWorkflowController::class,'voltar_analise_academica']);
Route::get('/editar_analise_academica/{estagio}', [EstagioWorkflowController::class,'editar_analise_academica']);

# Rotas Cancelamento
Route::get('/cancelar_estagio/{estagio}', [EstagioWorkflowController::class,'cancelar_estagio']);
Route::get('/cancelar_cancelamento/{estagio}', [EstagioWorkflowController::class,'cancelar_cancelamento']);

#Rotas Rescisão
Route::get('/retornar_rescisao/{estagio}', [EstagioWorkflowController::class,'retornar_rescisao']);
Route::post('/avaliacao/{estagio}', [EstagioWorkflowController::class,'avaliacao']);

# Rotas Concluido
Route::post('/rescisao/{estagio}', [EstagioWorkflowController::class,'rescisao']);
Route::post('/renovacao/{estagio}', [EstagioWorkflowController::class,'renovacao']);
Route::get('/iniciar_alteracao/{estagio}', [EstagioWorkflowController::class,'iniciar_alteracao']);

# Rotas Alteração
Route::post('/enviar_alteracao/{estagio}', [EstagioWorkflowController::class,'enviar_alteracao']);
Route::post('/analise_alteracao/{aditivo}', [EstagioWorkflowController::class,'analise_alteracao']);
Route::get('/voltar_aditivo/{estagio}', [EstagioWorkflowController::class,'voltar_aditivo']);

# Rotas Análise da Alteração
Route::post('/analise_tecnica_alteracao/{estagio}', [EstagioWorkflowController::class,'analise_tecnica_alteracao']);

# Rotas Menu dos pareceristas
Route::get('/parecer_merito', [PareceristaController::class,'parecerMerito']);
Route::get('/meus_pareceres', [PareceristaController::class,'meusPareceres']);
Route::get('/estagios_rescindidos', [PareceristaController::class,'estagiosRescindidos']);

#alterar parecerista
Route::post('/parecer_merito/{estagio}', [EstagioController::class,'alterarParecerista']);

#editar
Route::get('/editar/{estagio}', [EstagioController::class,'editar']);
Route::patch('/enviar_edicao/{estagio}', [EstagioWorkflowController::class,'enviarEdicao']);

#arquivos
Route::post('/files/store', [FileController::class,'store']);
Route::post('/files/store_relatorio', [FileController::class,'store_relatorio']);
Route::get('/files/ciente_relatorio/{file}', [FileController::class,'ciente_relatorio']);
Route::post('/files/destroy', [FileController::class,'destroy']);

# api
Route::get('info', [EstagioController::class, 'info'])->name('estagios.info');

# Novas páginas
Route::get('/reports', [ReportController::class, 'index']);
Route::get('report', [ReportController::class, 'report']);
Route::get('/estudantes', [EstudanteController::class, 'index']);

// settings
Route::get('/settings', [GeneralSettingsController::class, 'show']);
Route::post('/settings', [GeneralSettingsController::class, 'update']);

# Logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('can:admin');

app/Models/Estagio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\File;
use App\Models\Empresa;
use App\Models\User;
use App\Models\Aditivo;
use App\Models\Parecerista;
use App\Utils\ReplicadoUtils;
use App\Utils\AuditUtils;
use Uspdev\Replicado\Pessoa;
use Uspdev\Replicado\Graduacao;
use Carbon\Carbon;
use OwenIt\Auditing\Contracts\Auditable;
use Uspdev\Utils\Generic;
use App\Utils\Mapeamento;

class Estagio extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use HasFactory;

    protected $guarded = ['id'];

    public function arquivos(){
        return $this->hasMany(File::class);
    }

    public function avaliacao_empresaOptions(){
        return [
            'Positivo',
            'Negativo'
        ];
    }

    public function especifiquevtOptions(){
        return [
            'Mensal',
            'Diário'
        ];
    }

    public function tipobolsaOptions(){
        return [
            'Mensal',
            'Por Hora'
        ];
    }

    public function atividadespertinentesOptions(){
        return [
            'Sim',
            'Não',
            'Parcialmente'
        ];
    }

    public function buscastatusOptions(){
        return [
            'Sim',
            'Não',
            'Parcialmente'
        ];
    }

    public function pandemiahomeofficeOptions(){
        return [
            'Sim',
            'Não'
        ];
    }


    public function tipodeferimentoOptions(){
        return [
            'Deferido',
            'Deferido com Restrição',
            'Indeferido'
        ];
    }

    public function condicaodeferimentoOptions(){
        return [
            'Sim',
            'Não'
        ];
    }

    public function nomcurOptions(){
        return [
            'Letras',
            'Filosofia',
            'História',
            'Ciências Sociais',
            'Geografia',
        ];
    }

    public function area_estagio(){

        $areas = Area::distinct('area')->pluck('area')->toArray();

        $areas_fixas =  [
            'Ensino/Educação',
            'Editoração',
            'Tradução/ Interpretação',
            'Revisão, correção e/ou produção de textos',
            'Tecnologia -  Internet, mídias e ambientes digitais',
            'Administração (serviços gerais, secretariado, recepção, etc)',
            'Arte, Comunicação,Cultura e Museus',
            'Outra'
        ];

        return array_unique(array_merge($areas,$areas_fixas));
    }

    public function getDataInicialAttribute($value) {
        return implode('/',array_reverse(explode('-',$value)));
    }

    public function setDataInicialAttribute($value) {
        if (str_contains($value, '/')) {
            $this->attributes['data_inicial'] = implode('-',array_reverse(explode('/',$value)));
        } else {
            $this->attributes['data_inicial'] = $value;
        }

    }

    public function getDataFinalAttribute($value) {
        return implode('/',array_reverse(explode('-',$value)));
    }

    public function setDataFinalAttribute($value) {
        if (str_contains($value, '/')) {
            $this->attributes['data_final'] = implode('-',array_reverse(explode('/',$value)));
        } else {
            $this->attributes['data_final'] = $value;
        }
    }

    public function getRescisaoDataAttribute($value) {
        return implode('/',array_reverse(explode('-',$value)));
    }

    public function setRescisaoDataAttribute($value) {
       $this->attributes['rescisao_data'] = implode('-',array_reverse(explode('/',$value)));
    }

    public function setCnpjAttribute($value){
        $this->attributes['cnpj'] = preg_replace("/[^0-9]/", "", $value);
    }

    public function getEnderecoAttribute() {
        if($this->numero_usp) {
            // Formata endereço
            if($endereco = Pessoa::obterEndereco($this->numero_usp)) {
                return $endereco = "{$endereco['nomtiplgr']} {$endereco['epflgr']},
                    {$endereco['numlgr']} {$endereco['cpllgr']} -
                    {$endereco['nombro']} - {$endereco['cidloc']} -
                    {$endereco['sglest']} - CEP: {$endereco['codendptl']}";
            }
            return $endereco = 'não cadastrado';
        }
    }

    /* Método para auxiliar na construção de preposição com artigo definido */
    public function getArtigoDefinidoAttribute() {
        if($this->numero_usp){
            if(Pessoa::dump($this->numero_usp)['sexpes'] == "F") return "a";
            return "o";
        }
    }

    /* Método para auxiliar na construção de pronomes possessivos: seu/sua */
    public function getPronomePossessivoAttribute() {
        if($this->numero_usp){
            if(Pessoa::dump($this->numero_usp)['sexpes'] == "F") return "sua";
            return "seu";
        }
    }

    public function getMediaPonderadaAttribute() {
        if($this->numero_usp){
            return Graduacao::obterMediaPonderadaSuja($this->numero_usp);
        }else{
            return 'Média não disponível, favor entrar em contato com o Setor de Estágios';
        }
    }

    public function getPeriodoAttribute() {
        if($this->numero_usp)
            return ReplicadoUtils::periodo($this->numero_usp);
    }

    public function getSemestreAtualAttribute() {
        if($this->numero_usp)
            return ReplicadoUtils::semestreAtual($this->numero_usp);
    }

    public function getCursoAttribute() {
        if($this->nomcur){
            return $this->nomcur;
        }else{
            $curso = Graduacao::curso($this->numero_usp,8);
            if($curso) {
                return $curso['nomcur'];
            }else{
                return 'Sem infomação disponível';
            }
        }
    }

    public function getEmailAttribute() {
        if($this->numero_usp)
            return Pessoa::email($this->numero_usp);
    }

    public function getTipoIdentidadeAttribute() {
        if($this->numero_usp)
            return Pessoa::dump($this->numero_usp)['tipdocidf'];
    }

    public function getIdentidadeAttribute() {
        if($this->numero_usp)
            return Pessoa::dump($this->numero_usp)['numdocidf'];
    }

    public function getCpfAttribute() {
        if($this->numero_usp)
            $cpf = Pessoa::dump($this->numero_usp)['numcpf'];
            return str_pad($cpf, 11, 0, STR_PAD_LEFT);
    }

    public function getVerificarEstagioAttribute() {
        if($this->numero_usp)
            return Pessoa::verificarEstagioUSP($this->numero_usp);
    }

    public function getHabilitacaoAttribute() {
        if($this->numero_usp) {
            $curso = Graduacao::curso($this->numero_usp,8);
            if($curso) {
                return Graduacao::nomeHabilitacao($curso['codhab'], $curso['codcur']);
            }else{
                return 'Sem infomação disponível';
            }
        }
    }

    public function getGradeAttribute() {
        if($this->numero_usp)
            return ReplicadoUtils::grade($this->numero_usp);
    }

    public function getDuracaoAttribute() {
        return Generic::formata_periodo($this->data_inicial, $this->data_final);
    }

    public function getStatus(){
        $status = [
            'em_elaboracao' => [
                'name' => "Em Elaboração",
                'optional' => 'Empresa'
            ],
            'em_analise_tecnica' => [
                'name' => "Análise Técnica",
                'optional' => 'Setor de Graduação'
            ],

            'assinatura' => [
                'name' => "Assinatura",
                'optional' => 'Setor de Graduação'
            ],

            'em_analise_academica' => [
                'name' => "Parecer de Mérito",
                'optional' => 'Docente'
            ],
            'concluido' => [
                'name' => "Concluído",
                'optional' => 'Docente'
            ],
            'em_alteracao' => [
                'name' => "Aditivo de Alterações",
                'optional' => 'Empresa'
            ],
            'analise_alteracao_parecerista' => [
                'name' => "Aditivo de Alterações - Análise do Parecerista",
                'optional' => 'Docente'
            ],
            'rescisao' => [
                'name' => "Rescisão",
                'optional' => 'Empresa'
            ],
            'cancelado' => [
                'name' => "Cancelado",
                'optional' => 'Estágio Cancelado'
            ],
        ];

        return $status;
    }

    public function analise_academica_user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function areas()
    {
        return $this->belongsTo('App\Models\Area');
    }

    public function analise_tecnica_user()
    {
        return $this->belongsTo(User::class);
    }

    public function aditivos(){
        return $this->hasMany(Aditivo::class);
    }

    public function empresa()
    {
        return $this->belongsTo(Empresa::class,'cnpj','cnpj');
    }

    public function parecerista()
    {
        return $this->belongsTo(Parecerista::class,'numparecerista','numero_usp');
    }

    public function getPareceristaNomeAttribute() {
        if($this->numparecerista) {
            return Pessoa::nomeCompleto($this->numparecerista);
        }
    }

    public function getPareceristaEmailAttribute() {
        if($this->numparecerista)
            return Pessoa::email($this->numparecerista);
    }

    public function mapeamento($chave) {
        return Mapeamento::map($chave);
    }
}

resources/views/estagios/partials/assinatura.blade.php
<br>
<div style="text-align: center;"><b style="color:red">Aviso Importante:</b> O termo deve ser entregue assinado para a instituição no mínimo 10 dias úteis antes do início do período do estágio no email <b>{{ $settings->email }}</b></div>
<br>

@if(!empty($estagio->analise_tecnica))
    <b>Última análise técnica do setor de graduação:</b> {{$estagio->analise_tecnica}}
    <br>
@endif

@can('admin')

<div class="card">
    <div class="card-header"><b>Ações</b></div> 
    <div class="card-body">
        <a class="btn btn-success" onClick="return confirm('Tem certeza que deseja retornar o estágio para a análise técnica?')" href="/retornar_assinatura/{{$estagio->id}}">
        <i class="fas fa-undo"></i> 
        Retornar estágio para análise técnica </a> <br>
    </div>
</div>
<br>

@include('estagios.partials.gerenciar_estagio')

@endcan('admin')

resources/views/estagios/partials/cancelado.blade.php
<div style="text-align: center;"><h3><b>Estágio Cancelado</b></h3></div>

    @can('admin')
    <br><br>
    <a class="btn btn-warning" onClick="return confirm('Tem certeza que deseja reativar o estágio?')" href="/cancelar_cancelamento/{{$estagio->id}}">
        Reativar Estágio </a>

    @endcan

resources/views/estagios/partials/gerenciar_estagio.blade.php
<!-- Area de aprovação de aditivos do parecerista -->

@can('parecerista')
@foreach($estagio->aditivos
    ->where('aprovado_graduacao','===',null)
    ->where('comentario_graduacao','!=',null)
    ->where('comentario_parecerista','=',null)
    ->where('aprovado_parecerista','=',null) as $aditivo)

        <div class="card">
            <div class="card-header"><b>Aditivo pendente de análise pelo parecerista</b></div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 form-group">
                            <form method="POST" action="/analise_alteracao/{{$aditivo->id}}">
                                @csrf
                                <b>Aditivo de Alteração Pendente:</b> {{ $aditivo->alteracao }}<br><br>

                                <b>Comentário do setor de graduação sobre o aditivo:</b> {{ $aditivo->comentario_graduacao }}<br><br>

                                <label for="comentario_parecerista">Favor especificar motivo do deferimento/indeferimento: </label><br>
                                <textarea name="comentario_parecerista" rows="5" cols="60"></textarea><br>

                                <button type="submit" class="btn btn-success" name="analise_alteracao_action" value="parecerista_deferir_alteracao"
                                    onClick="return confirm('Tem certeza que deseja deferir o aditivo?')" >
                                    Deferir Aditivo
                                </button>

                                <button type="submit" class="btn btn-warning" name="analise_alteracao_action" value="parecerista_indeferir_alteracao"
                                    onClick="return confirm('Tem certeza que deseja indeferir o aditivo?')" >
                                    Indeferir Aditivo
                                </button>

                            </form>
                        </div>
                    </div>
            </div></div>


@endforeach
@endcan('parecerista')

<!-- Area do administrador -->

@can('admin')
<div class="card">
    <div class="card-header"><b>Área de Administrador</b></div>
      <div class="card-body">
            <div class="row">
            <div class="col-4 form-group">
                <b>Gerenciar Parecerista:</b><br><br>
                <form method="POST" action="/parecer_merito/{{$estagio->id}}">
                @csrf

                <select name="numparecerista">
                    <option value="" selected=""> - Selecione  -</option>
                    @foreach (\App\Models\Parecerista::all() as $parecerista)

                        @if (old('numparecerista') == '' and isset($estagio->numparecerista))
                            <option value="{{$parecerista->numero_usp}}" {{ ( $estagio->numparecerista == $parecerista->numero_usp) ? 'selected' : ''}}>
                                {{$parecerista->numero_usp}} - {{ $parecerista->nome }}
                            </option>
                        @else
                            <option value="{{$parecerista->numero_usp}}" {{ ( old('numparecerista') == $parecerista->numero_usp) ? 'selected' : ''}}>
                                {{$parecerista->numero_usp}} - {{ $parecerista->nome }}
                            </option>
                        @endif

                    @endforeach
                </select>

                @if(($estagio->numparecerista)!=null)
                    <br>
                    <b>Nome:</b> {{ $estagio->parecerista_nome }}<br>
                    <b>Email Cadastrado:</b> {{ $estagio->parecerista_email }}</b><br>
                @endif

                <br>
                <button type="submit" class="btn btn-success">Alterar Número</button>
                </form>
            </div>

                <div class="col-4 form-group">
                    <b>Gerar Documentos:</b><br><br>

                    @if(($estagio->desempenhoacademico)!=null)
                        <a href="/pdfs/parecer/{{$estagio->id}}"target="_blank" >
                        <i class="fas fa-file-pdf"></i> </a>
                        Gerar PDF do Parecer de Mérito
                    @endif

                    @if(is_null($estagio->renovacao_parent_id))
                        <br>
                        <a href="/pdfs/termo/{{$estagio->id}}"target="_blank" >
                        <i class="fas fa-file-pdf"></i> </a>
                        Gerar PDF dos Documentos de Estágio
                    @else
                        <br>
                        <a href="/pdfs/renovacao/{{$estagio->id}}" target="_blank" >
                        <i class="fas fa-file-pdf"></i> </a>
                        Gerar PDF dos Documentos de Estágio para Renovação
                    @endif

                    @if(($estagio->aditivos)->isNotEmpty())
                        <br>
                        <a href="/pdfs/aditivo/{{$estagio->id}}" target="_blank" >
                        <i class="fas fa-file-pdf"></i> </a>
                        Gerar PDF do Parecer de Alteração
                    @endif

                    @if(($estagio->status)=='rescisao')
                        <br>
                        <a href="/pdfs/rescisao/{{$estagio->id}}" target="_blank" >
                        <i class="fas fa-file-pdf"></i> </a>
                        Gerar PDF do Termo de Rescisão
                    @endif

                    <br>
                </div>

                <div class="col-4 form-group">
                    <b>Opções de Envio de Email automático:</b><br><br>
                    <a onClick="return confirm('Tem certeza que deseja um email para o parecerista?')" href="/emails/enviar_para_parecerista/{{$estagio->id}}">
                    <i class="fas fa-envelope-open-text"></i> </a>
                    Enviar e-mail com parecer em anexo para o e-mail USP do parecerista

                    @if(is_null($estagio->renovacao_parent_id))
                        <br>
                        <a onClick="return confirm('Tem certeza que deseja um email para a empresa?')" href="/emails/enviar_para_analise_tecnica/{{$estagio->id}}">
                        <i class="fas fa-envelope-open-text"></i> </a>
                        Enviar E-mail contendo o Termo de Ciência para a empresa   <br>

                        <a onClick="return confirm('Tem certeza que deseja um email para o estudante?')" href="/emails/enviar_para_estudante/{{$estagio->id}}">
                        <i class="fas fa-envelope-open-text"></i> </a>
                        Enviar E-mail contendo o Termo de Ciência para o estudante


                    @else
                        <br>
                        <a onClick="return confirm('Tem certeza que deseja um email para a empresa?')" href="/emails/enviar_para_analise_tecnica_renovacao/{{$estagio->id}}">
                        <i class="fas fa-envelope-open-text"></i> </a>
                        Enviar E-mail contendo o Termo de Ciência para Renovação para a empresa
                    @endif

                    @if(($estagio->aditivos)->isNotEmpty())
                        <br>
                        <a onClick="return confirm('Tem certeza que deseja um email para a empresa?')" href="/emails/alteracao_empresa/{{$estagio->id}}">
                        <i class="fas fa-envelope-open-text"></i> </a>
                        Enviar E-mail contendo as alterações para a empresa.
                    @endif

            </div>

            @foreach($estagio->aditivos->where('aprovado_graduacao','=',0)->where('comentario_graduacao','=',null) as $aditivo)


            <div class="row">
                <div class="col-12 form-group">
                <br><hr><br>
                    <form method="POST" action="/analise_alteracao/{{$aditivo->id}}">
                        @csrf
                        <b>Aditivo de Alteração Pendente:</b> {{ $aditivo->alteracao }}<br><br>

                        @if(($aditivo->comentario_graduacao)!=null)
                            <b>Avaliação do parecerista sobre o aditivo:</b> {{ $aditivo->comentario_graduacao }}<br><br>

                            <b>Comentário do parecerista sobre o aditivo:</b> {{ $aditivo->comentario_graduacao }}<br><br>
                        @endif



                        <label for="comentario_graduacao">Em caso de indeferimento ou solicitação de análise
                        por parte do parecerista, especifique o motivo: </label><br>
                        <textarea name="comentario_graduacao" rows="5" cols="60"></textarea><br>

                        <button type="submit" class="btn btn-success" name="analise_alteracao_action" value="deferir_alteracao"
                            onClick="return confirm('Tem certeza que deseja deferir o aditivo?')" >
                            Deferir Aditivo
                        </button>

                        <button type="submit" class="btn btn-warning" name="analise_alteracao_action" value="indeferir_alteracao"
                            onClick="return confirm('Tem certeza que deseja indeferir o aditivo?')" >
                            Indeferir Aditivo
                        </button>

                        <button type="submit" class="btn btn-info" name="analise_alteracao_action" value="solicitar_parecerista"
                            onClick="return confirm('Tem certeza que deseja solicitar avaliação do parecerista?')" >
                            Solicitar Avaliação do Parecerista
                        </button>

                    </form>
                </div>
            </div>

            @endforeach

            @foreach($estagio->aditivos
            ->where('aprovado_graduacao','===',null)
            ->where('comentario_graduacao','!=',null)
            ->where('comentario_parecerista','!=',null) as $aditivo)

            <div class="row">
                <div class="col-12 form-group">
                    <form method="POST" action="/analise_alteracao/{{$aditivo->id}}">
                        @csrf
                        <br>
                        <b>Aditivo de Alteração Pendente:</b> {{ $aditivo->alteracao }}<br><br>

                        <b>Avaliação do parecerista sobre o aditivo:</b>
                        @if(($aditivo->aprovado_parecerista)==0)
                        Aditivo Reprovado
                        @elseif(($aditivo->aprovado_parecerista)==1)
                        Aditivo Aprovado
                        @endif

                        <br><br>

                        <b>Comentário do parecerista sobre o aditivo:</b> {{ $aditivo->comentario_parecerista }}<br><br>

                        <button type="submit" class="btn btn-success" name="analise_alteracao_action" value="deferir_alteracao_posparecerista"
                            onClick="return confirm('Tem certeza que deseja deferir o aditivo?')" >
                            Deferir Aditivo
                        </button>

                        <button type="submit" class="btn btn-warning" name="analise_alteracao_action" value="indeferir_alteracao_posparecerista"
                            onClick="return confirm('Tem certeza que deseja indeferir o aditivo?')" >
                            Indeferir Aditivo
                        </button>

                    </form>
                </div>
            </div>

            @endforeach

</div>
@endcan('admin')